### ISSUE TITLE
Imagem pro repo

### ISSUE THREAD

**Issue by marimeireles** [cppbrasil/material-de-aprendizado#29]
A gente podia botar uma imagem bonitinha também. Tipo a mesma do grupo de Telegram ou com uma coisinha do Brasil(?)
Não sei, o que acham?

**Comment by marimeireles** [comment]
Me disponho a photoshopar, só preciso de ideias.

**Comment by patrickelectric** [comment]
Fiz um negócio meio loco aqui:
![image](https://user-images.githubusercontent.com/1215497/78454617-8ac78380-766f-11ea-8ff2-a970010a57cb.png)

mas acho que ficou ruim de le
[ISO_C++_Logo_Brasil.tar.gz](https://github.com/cppbrasil/material-de-aprendizado/files/4432109/ISO_C%2B%2B_Logo_Brasil.tar.gz)

**Comment by marimeireles** [comment]
Ah, eu achei daora! :)

**Comment by patrickelectric** [comment]
Alternativa:
![image](https://user-images.githubusercontent.com/1215497/78455381-6fab4280-7674-11ea-96af-cf8ac6ed9466.png)


[brasil-cpp.tar.gz](https://github.com/cppbrasil/material-de-aprendizado/files/4432091/brasil-cpp.tar.gz)

**Comment by tarcisioe** [comment]
Fiz uma sugestão de acordo com o texto do isocpp.org, que diz:

"We do not normally approve modified versions of the logo; instead, most uses should use the unmodified logo beside or near any other art without overlap."

![cppbrasillogo](https://user-images.githubusercontent.com/774694/78455708-4e4b5600-7676-11ea-94af-e0f9aa54094e.png)

[cppbrasil.tar.gz](https://github.com/cppbrasil/material-de-aprendizado/files/4432121/cppbrasil.tar.gz)

**Comment by tarcisioe** [comment]
Outra ideia aqui

![cppbrasillogo-v2](https://user-images.githubusercontent.com/774694/78460393-d2153a80-7696-11ea-9ffb-a29dc37e2852.png)

[cppbrasil-v2.tar.gz](https://github.com/cppbrasil/material-de-aprendizado/files/4432355/cppbrasil-v2.tar.gz)

**Comment by marimeireles** [comment]
Fechado porque temos https://github.com/cppbrasil/logo
