### ISSUE TITLE
Alterar a Descrição do Repositório

### ISSUE THREAD

**Issue by geyslan** [cppbrasil/material-de-aprendizado#48]
Alterar incluindo C:
Coleção de materiais e links para aprendizado de **C** e C++, em português ou inglês.

**Comment by fafato1** [comment]
Feito a mudança

**Comment by tarcisioe** [comment]
@fafato1 acho que o Readme tem o mesmo problema.

**Comment by fafato1** [comment]
@tarcisioe resolvido
